version: '3.7'
services:
  matterbridge:
    image: 42wim/matterbridge:latest
    restart: unless-stopped
    volumes:
    - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml:ro
    command: -debug
